### PR TITLE
Initial fuzzing support and fixes

### LINKED ISSUE #8: Stability improvements
- [x]  run fuzzing
- [x]  handle filesystem full errors
- [x] https://github.com/Nitrokey/oath-authenticator/issues/5 handle parsing errors
- [x] check if other syscalls can fail
- [ ] run longer load test session
- [x] make parsing asserts working in the release mode, and make them recoverable errors

### PR DESCRIPTION
**Pull request by szszszsz**
Add initial fuzzing support and fixes found during its executions.

Corpus generated with the pynitrokey API tests (not included here). Each input file contains single command only at this point. No new errors found after 20 minutes, with 11 jobs set. A fork of Flexiber was used, which had the crashing `todo()` replaced with returning Error code.

Future work / to discuss:
- [ ] might be worth to run it longer, or in CI
- [ ] extend the corpus to have more commands - Select, Validate, CalculateAll, SendRemaining
- [x] ~disable not tested commands (as mentioned)~ skipped
- [x] add coverage report generation
- [ ] extend the corpus to run multiple commands at a time
- [ ] dockerize/reuse fuzz setup
- [x] something better than `assertfn` ?

Inspired by the opcard-rs [fuzzing implementation](https://github.com/Nitrokey/opcard-rs/tree/main/fuzz).

Fixes #8

### CODE REVIEW

**Comment by szszszsz** [comment]
@sosthene-nitrokey Any ideas how to fix that?
```
$ cd fuzz && make fuzz-cov
# ...
Merging raw coverage data...
Coverage data merged and saved in "/home/sz/work/OTP/oath-authenticator/fuzz/coverage/fuzz_target_1/coverage.profdata".
llvm-cov show --format=html \
        --instr-profile=coverage/fuzz_target_1/coverage.profdata \
         /tmp/cargo/x86_64-unknown-linux-gnu/release/fuzz_target_1 \
        > fuzz_coverage.html
error: /tmp/cargo/x86_64-unknown-linux-gnu/release/fuzz_target_1: Failed to load coverage: unsupported instrumentation profile format version
```

**Comment by sosthene-nitrokey** [comment]
The proper way to invoke it would probably be [cargo-binutils](https://github.com/rust-embedded/cargo-binutils), but I'm not sure if it's worth it adding it to the pipeline image

**Comment by szszszsz** [comment]
Yes, this worked for me, thanks!

File: src/lib.rs [hunk 1]
```diff
@@ -32,3 +32,11 @@ pub const UP_TIMEOUT_MILLISECONDS: u32 = 15 * 1000;
 //     PIV = b'\xa0\x00\x00\x03\x08'
 //     U2F = b'\xa0\x00\x00\x06\x47\x2f\x00\x01'  # Official
 //     U2F_YUBICO = b'\xa0\x00\x00\x05\x27\x10\x02'  # Yubico - No longer used
+
+
+fn assertfn<T>(cond: bool, err: T) ->  core::result::Result<(), T> {
```
Comment (sosthene-nitrokey) [inline src/lib.rs:37]: I'd rather call it "verify" or "ensure". To me assert implies crashing.

File: fuzz/fuzz_targets/fuzz_target_1.rs [hunk 2]
```diff
@@ -0,0 +1,14 @@
+#![no_main]
+
+use libfuzzer_sys::fuzz_target;
+
+fuzz_target!(|data: &[u8]| {
```
Comment (sosthene-nitrokey) [inline fuzz/fuzz_targets/fuzz_target_1.rs:5]: I think we want  to be chain multiple commands within one round of fuzzing. Otherwise many code paths can't be explored, for example for authentication, and modification/deletion. You can use `Arbitrary` to get a vec of commands.

Also does Oath need authentication for some command? I think it would be very hard for the fuzzer find the correct password so it should probably be in a seed corpus.

**Review by sosthene-nitrokey — CHANGES_REQUESTED** [review]
Is the empty lib.rs required?
